# Generated by Django 4.2.7 on 2025-12-03 20:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoommateProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('budget_max', models.FloatField(default=0)),
                ('rent_ask', models.FloatField(default=0)),
                ('cleanliness', models.CharField(choices=[('messy', 'Messy'), ('moderate', 'Moderate'), ('clean', 'Clean'), ('very_clean', 'Very Clean')], default='moderate', max_length=20)),
                ('sleep_schedule', models.CharField(choices=[('early_bird', 'Early Bird'), ('night_owl', 'Night Owl'), ('flexible', 'Flexible')], default='flexible', max_length=20)),
                ('interests', models.JSONField(blank=True, default=list)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('major', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='roommate_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
