# Generated by Django 4.2.7 on 2025-12-03 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_roommateprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='roommateprofile',
            name='avatar',
            field=models.TextField(blank=True, null=True),
        ),
    ]
