const express = require('express');
const router = express.Router();
const imageAnalysisService = require('../services/imageAnalysis');

// Sample property database
const properties = [
  {
    id: 1,
    title: 'Modern 1BR Near Campus',
    address: '123 College St, Toronto, ON',
    city: 'Toronto',
    province: 'ON',
    rent: 1650,
    bedrooms: 1,
    bathrooms: 1,
    sqft: 550,
    image: '🏢',
    available: 'Available Now',
    utilities: 'Included',
    parking: true,
    laundry: 'In-unit',
    petFriendly: false,
    furnished: false,
    distance: 0.5,
    amenities: ['WiFi', 'Gym', 'Storage'],
    landlord: 'Property Management Co.',
    description: 'Bright and modern 1-bedroom apartment close to campus. Perfect for students!'
  },
  {
    id: 2,
    title: 'Cozy Studio Downtown',
    address: '456 Queen St W, Toronto, ON',
    city: 'Toronto',
    province: 'ON',
    rent: 1400,
    bedrooms: 0,
    bathrooms: 1,
    sqft: 400,
    image: '🏠',
    available: 'Dec 1, 2024',
    utilities: 'Not Included',
    parking: false,
    laundry: 'In-building',
    petFriendly: true,
    furnished: true,
    distance: 1.2,
    amenities: ['WiFi', 'Balcony'],
    landlord: 'John Smith',
    description: 'Fully furnished studio in the heart of downtown. Great for students who want city life!'
  },
  {
    id: 3,
    title: 'Spacious 2BR Apartment',
    address: '789 Bloor St, Toronto, ON',
    city: 'Toronto',
    province: 'ON',
    rent: 2200,
    bedrooms: 2,
    bathrooms: 1,
    sqft: 850,
    image: '🏘️',
    available: 'Available Now',
    utilities: 'Included',
    parking: true,
    laundry: 'In-unit',
    petFriendly: true,
    furnished: false,
    distance: 0.8,
    amenities: ['WiFi', 'Gym', 'Pool', 'Storage', 'Balcony'],
    landlord: 'Urban Living Properties',
    description: 'Perfect for sharing! Spacious 2-bedroom with all amenities. Great for roommates!'
  },
  {
    id: 4,
    title: 'Affordable 1BR Basement',
    address: '321 Spadina Ave, Toronto, ON',
    city: 'Toronto',
    province: 'ON',
    rent: 1200,
    bedrooms: 1,
    bathrooms: 1,
    sqft: 500,
    image: '🏡',
    available: 'Jan 1, 2025',
    utilities: 'Not Included',
    parking: true,
    laundry: 'Shared',
    petFriendly: false,
    furnished: false,
    distance: 1.5,
    amenities: ['WiFi', 'Storage'],
    landlord: 'Private Owner',
    description: 'Budget-friendly basement apartment. Quiet neighborhood, perfect for studying.'
  },
  {
    id: 5,
    title: 'Luxury 1BR Condo',
    address: '555 Bay St, Toronto, ON',
    city: 'Toronto',
    province: 'ON',
    rent: 2400,
    bedrooms: 1,
    bathrooms: 1,
    sqft: 650,
    image: '🏙️',
    available: 'Available Now',
    utilities: 'Included',
    parking: true,
    laundry: 'In-unit',
    petFriendly: true,
    furnished: true,
    distance: 2.0,
    amenities: ['WiFi', 'Gym', 'Pool', 'Concierge', 'Rooftop Terrace'],
    landlord: 'Luxury Condos Inc.',
    description: 'High-end condo with stunning city views. All amenities included!'
  },
  {
    id: 6,
    title: 'Student-Friendly 2BR',
    address: '888 Harbord St, Toronto, ON',
    city: 'Toronto',
    province: 'ON',
    rent: 1900,
    bedrooms: 2,
    bathrooms: 1,
    sqft: 750,
    image: '🏘️',
    available: 'Available Now',
    utilities: 'Not Included',
    parking: false,
    laundry: 'In-building',
    petFriendly: false,
    furnished: false,
    distance: 0.3,
    amenities: ['WiFi', 'Study Room'],
    landlord: 'Student Housing Co.',
    description: 'Perfect for students! Super close to campus. Ideal for 2 roommates.'
  },
  {
    id: 7,
    title: 'Bright Studio Apartment',
    address: '234 Yonge St, Toronto, ON',
    city: 'Toronto',
    province: 'ON',
    rent: 1550,
    bedrooms: 0,
    bathrooms: 1,
    sqft: 450,
    image: '🏠',
    available: 'Available Now',
    utilities: 'Included',
    parking: false,
    laundry: 'In-building',
    petFriendly: false,
    furnished: false,
    distance: 1.8,
    amenities: ['WiFi', 'Gym'],
    landlord: 'Downtown Properties',
    description: 'Bright studio with large windows. Great natural light!'
  },
  {
    id: 8,
    title: 'Cozy 1BR with Balcony',
    address: '567 Dundas St W, Toronto, ON',
    city: 'Toronto',
    province: 'ON',
    rent: 1750,
    bedrooms: 1,
    bathrooms: 1,
    sqft: 600,
    image: '🏢',
    available: 'Dec 15, 2024',
    utilities: 'Not Included',
    parking: true,
    laundry: 'In-unit',
    petFriendly: true,
    furnished: false,
    distance: 1.0,
    amenities: ['WiFi', 'Balcony', 'Storage'],
    landlord: 'City Living Realty',
    description: 'Lovely 1-bedroom with private balcony. Pet-friendly building!'
  },
  // Vancouver Properties
  {
    id: 9,
    title: 'Downtown Vancouver Studio',
    address: '789 Granville St, Vancouver, BC',
    city: 'Vancouver',
    province: 'BC',
    rent: 1800,
    bedrooms: 0,
    bathrooms: 1,
    sqft: 420,
    image: '🏙️',
    available: 'Available Now',
    utilities: 'Included',
    parking: false,
    laundry: 'In-building',
    petFriendly: false,
    furnished: true,
    distance: 0.8,
    amenities: ['WiFi', 'Gym', 'Rooftop'],
    landlord: 'Vancouver Properties Ltd',
    description: 'Modern studio in the heart of downtown Vancouver. Walking distance to everything!'
  },
  {
    id: 10,
    title: 'Kitsilano 2BR Beach House',
    address: '234 Cornwall Ave, Vancouver, BC',
    city: 'Vancouver',
    province: 'BC',
    rent: 2800,
    bedrooms: 2,
    bathrooms: 2,
    sqft: 900,
    image: '🏖️',
    available: 'Jan 1, 2025',
    utilities: 'Not Included',
    parking: true,
    laundry: 'In-unit',
    petFriendly: true,
    furnished: false,
    distance: 2.5,
    amenities: ['WiFi', 'Beach Access', 'Patio', 'Storage'],
    landlord: 'Coastal Living Realty',
    description: 'Beautiful 2-bedroom near Kitsilano Beach. Perfect for beach lovers!'
  },
  {
    id: 11,
    title: 'UBC Campus 1BR',
    address: '456 Wesbrook Mall, Vancouver, BC',
    city: 'Vancouver',
    province: 'BC',
    rent: 1600,
    bedrooms: 1,
    bathrooms: 1,
    sqft: 500,
    image: '🏫',
    available: 'Available Now',
    utilities: 'Included',
    parking: false,
    laundry: 'In-building',
    petFriendly: false,
    furnished: false,
    distance: 0.2,
    amenities: ['WiFi', 'Study Room', 'Gym'],
    landlord: 'UBC Student Housing',
    description: 'Steps from UBC campus! Perfect for students. Quiet building.'
  },
  // Montreal Properties
  {
    id: 12,
    title: 'Plateau 3½ Apartment',
    address: '123 Rue Saint-Denis, Montreal, QC',
    city: 'Montreal',
    province: 'QC',
    rent: 1200,
    bedrooms: 1,
    bathrooms: 1,
    sqft: 550,
    image: '🎨',
    available: 'Available Now',
    utilities: 'Not Included',
    parking: false,
    laundry: 'Shared',
    petFriendly: true,
    furnished: false,
    distance: 1.5,
    amenities: ['WiFi', 'Hardwood Floors'],
    landlord: 'Montreal Rentals Inc',
    description: 'Charming apartment in the Plateau. Artistic neighborhood with cafes and shops.'
  },
  {
    id: 13,
    title: 'McGill Area Studio',
    address: '789 Rue Sherbrooke O, Montreal, QC',
    city: 'Montreal',
    province: 'QC',
    rent: 950,
    bedrooms: 0,
    bathrooms: 1,
    sqft: 380,
    image: '🏠',
    available: 'Dec 1, 2024',
    utilities: 'Included',
    parking: false,
    laundry: 'In-building',
    petFriendly: false,
    furnished: true,
    distance: 0.3,
    amenities: ['WiFi', 'Heating Included'],
    landlord: 'Student Living Co',
    description: 'Affordable studio near McGill University. All utilities included!'
  },
  {
    id: 14,
    title: 'Old Montreal Loft',
    address: '456 Rue Notre-Dame, Montreal, QC',
    city: 'Montreal',
    province: 'QC',
    rent: 2100,
    bedrooms: 2,
    bathrooms: 1,
    sqft: 850,
    image: '🏛️',
    available: 'Available Now',
    utilities: 'Not Included',
    parking: true,
    laundry: 'In-unit',
    petFriendly: true,
    furnished: false,
    distance: 3.0,
    amenities: ['WiFi', 'Exposed Brick', 'High Ceilings', 'Balcony'],
    landlord: 'Heritage Properties',
    description: 'Stunning loft in historic Old Montreal. Unique character and charm!'
  },
  // Calgary Properties
  {
    id: 15,
    title: 'Downtown Calgary 1BR',
    address: '234 7th Ave SW, Calgary, AB',
    city: 'Calgary',
    province: 'AB',
    rent: 1400,
    bedrooms: 1,
    bathrooms: 1,
    sqft: 600,
    image: '🏢',
    available: 'Available Now',
    utilities: 'Included',
    parking: true,
    laundry: 'In-unit',
    petFriendly: false,
    furnished: false,
    distance: 1.2,
    amenities: ['WiFi', 'Gym', 'Concierge', 'Pool'],
    landlord: 'Calgary Tower Properties',
    description: 'Modern downtown condo with amazing city views. All amenities included!'
  },
  {
    id: 16,
    title: 'University District 2BR',
    address: '567 University Dr NW, Calgary, AB',
    city: 'Calgary',
    province: 'AB',
    rent: 1650,
    bedrooms: 2,
    bathrooms: 1,
    sqft: 750,
    image: '🏘️',
    available: 'Jan 1, 2025',
    utilities: 'Not Included',
    parking: true,
    laundry: 'In-building',
    petFriendly: true,
    furnished: false,
    distance: 0.5,
    amenities: ['WiFi', 'Storage', 'Bike Room'],
    landlord: 'University Housing',
    description: 'Perfect for students or young professionals. Close to U of C campus.'
  },
  // Ottawa Properties
  {
    id: 17,
    title: 'ByWard Market Studio',
    address: '123 York St, Ottawa, ON',
    city: 'Ottawa',
    province: 'ON',
    rent: 1300,
    bedrooms: 0,
    bathrooms: 1,
    sqft: 400,
    image: '🏛️',
    available: 'Available Now',
    utilities: 'Included',
    parking: false,
    laundry: 'In-building',
    petFriendly: false,
    furnished: true,
    distance: 1.8,
    amenities: ['WiFi', 'Historic Building'],
    landlord: 'Capital Properties',
    description: 'Charming studio in the heart of ByWard Market. Walk to Parliament!'
  },
  {
    id: 18,
    title: 'Glebe 2BR Townhouse',
    address: '456 Bank St, Ottawa, ON',
    city: 'Ottawa',
    province: 'ON',
    rent: 2200,
    bedrooms: 2,
    bathrooms: 2,
    sqft: 1000,
    image: '🏘️',
    available: 'Dec 15, 2024',
    utilities: 'Not Included',
    parking: true,
    laundry: 'In-unit',
    petFriendly: true,
    furnished: false,
    distance: 2.0,
    amenities: ['WiFi', 'Backyard', 'Storage', 'Fireplace'],
    landlord: 'Glebe Realty',
    description: 'Spacious townhouse in desirable Glebe neighborhood. Family-friendly!'
  },
  // More Toronto Properties
  {
    id: 19,
    title: 'Yorkville Luxury 1BR',
    address: '890 Bay St, Toronto, ON',
    city: 'Toronto',
    province: 'ON',
    rent: 2600,
    bedrooms: 1,
    bathrooms: 1,
    sqft: 700,
    image: '💎',
    available: 'Available Now',
    utilities: 'Included',
    parking: true,
    laundry: 'In-unit',
    petFriendly: true,
    furnished: true,
    distance: 1.5,
    amenities: ['WiFi', 'Gym', 'Pool', 'Concierge', 'Spa', 'Rooftop'],
    landlord: 'Luxury Living Toronto',
    description: 'Ultra-luxury condo in prestigious Yorkville. 5-star amenities!'
  },
  {
    id: 20,
    title: 'Annex Student House',
    address: '234 Madison Ave, Toronto, ON',
    city: 'Toronto',
    province: 'ON',
    rent: 850,
    bedrooms: 1,
    bathrooms: 1,
    sqft: 450,
    image: '🏡',
    available: 'Available Now',
    utilities: 'Not Included',
    parking: false,
    laundry: 'Shared',
    petFriendly: false,
    furnished: false,
    distance: 0.6,
    amenities: ['WiFi', 'Backyard Access'],
    landlord: 'Student Housing Co-op',
    description: 'Affordable room in shared house near U of T. Great student community!'
  },
  {
    id: 21,
    title: 'Liberty Village 2BR',
    address: '567 Liberty St, Toronto, ON',
    city: 'Toronto',
    province: 'ON',
    rent: 2400,
    bedrooms: 2,
    bathrooms: 2,
    sqft: 900,
    image: '🏙️',
    available: 'Jan 1, 2025',
    utilities: 'Included',
    parking: true,
    laundry: 'In-unit',
    petFriendly: true,
    furnished: false,
    distance: 3.5,
    amenities: ['WiFi', 'Gym', 'Pool', 'Balcony', 'Storage'],
    landlord: 'Liberty Properties',
    description: 'Modern condo in trendy Liberty Village. Close to restaurants and shops!'
  },
  {
    id: 22,
    title: 'Scarborough Basement Suite',
    address: '789 Kennedy Rd, Toronto, ON',
    city: 'Toronto',
    province: 'ON',
    rent: 1100,
    bedrooms: 1,
    bathrooms: 1,
    sqft: 500,
    image: '🏡',
    available: 'Available Now',
    utilities: 'Included',
    parking: true,
    laundry: 'Shared',
    petFriendly: false,
    furnished: false,
    distance: 8.0,
    amenities: ['WiFi', 'Separate Entrance'],
    landlord: 'Private Owner',
    description: 'Affordable basement suite in Scarborough. Utilities included!'
  },
  // Edmonton Properties
  {
    id: 23,
    title: 'Whyte Ave 1BR',
    address: '123 Whyte Ave, Edmonton, AB',
    city: 'Edmonton',
    province: 'AB',
    rent: 1250,
    bedrooms: 1,
    bathrooms: 1,
    sqft: 550,
    image: '🏢',
    available: 'Available Now',
    utilities: 'Not Included',
    parking: true,
    laundry: 'In-building',
    petFriendly: true,
    furnished: false,
    distance: 1.0,
    amenities: ['WiFi', 'Gym', 'Storage'],
    landlord: 'Edmonton Rentals',
    description: 'Vibrant Whyte Avenue location. Close to U of A and nightlife!'
  },
  {
    id: 24,
    title: 'Downtown Edmonton Studio',
    address: '456 Jasper Ave, Edmonton, AB',
    city: 'Edmonton',
    province: 'AB',
    rent: 1100,
    bedrooms: 0,
    bathrooms: 1,
    sqft: 400,
    image: '🏠',
    available: 'Dec 1, 2024',
    utilities: 'Included',
    parking: false,
    laundry: 'In-building',
    petFriendly: false,
    furnished: true,
    distance: 2.0,
    amenities: ['WiFi', 'Heating Included'],
    landlord: 'City Centre Properties',
    description: 'Cozy downtown studio. Perfect for students or young professionals!'
  },
  // Winnipeg Properties
  {
    id: 25,
    title: 'Osborne Village 2BR',
    address: '234 Osborne St, Winnipeg, MB',
    city: 'Winnipeg',
    province: 'MB',
    rent: 1300,
    bedrooms: 2,
    bathrooms: 1,
    sqft: 800,
    image: '🏘️',
    available: 'Available Now',
    utilities: 'Not Included',
    parking: true,
    laundry: 'In-unit',
    petFriendly: true,
    furnished: false,
    distance: 1.5,
    amenities: ['WiFi', 'Balcony', 'Storage'],
    landlord: 'Winnipeg Housing',
    description: 'Spacious 2-bedroom in trendy Osborne Village. Great neighborhood!'
  },
  {
    id: 26,
    title: 'U of M Campus Studio',
    address: '567 University Cres, Winnipeg, MB',
    city: 'Winnipeg',
    province: 'MB',
    rent: 900,
    bedrooms: 0,
    bathrooms: 1,
    sqft: 350,
    image: '🏫',
    available: 'Available Now',
    utilities: 'Included',
    parking: false,
    laundry: 'In-building',
    petFriendly: false,
    furnished: false,
    distance: 0.3,
    amenities: ['WiFi', 'Study Room'],
    landlord: 'Student Housing Manitoba',
    description: 'Steps from University of Manitoba. Perfect for students!'
  },
  // Halifax Properties
  {
    id: 27,
    title: 'Halifax Waterfront 1BR',
    address: '123 Lower Water St, Halifax, NS',
    city: 'Halifax',
    province: 'NS',
    rent: 1500,
    bedrooms: 1,
    bathrooms: 1,
    sqft: 600,
    image: '⚓',
    available: 'Available Now',
    utilities: 'Included',
    parking: false,
    laundry: 'In-building',
    petFriendly: true,
    furnished: false,
    distance: 2.0,
    amenities: ['WiFi', 'Waterfront View', 'Gym'],
    landlord: 'Maritime Properties',
    description: 'Beautiful waterfront apartment with harbor views. Prime location!'
  },
  {
    id: 28,
    title: 'Dalhousie Area 2BR',
    address: '456 LeMarchant St, Halifax, NS',
    city: 'Halifax',
    province: 'NS',
    rent: 1400,
    bedrooms: 2,
    bathrooms: 1,
    sqft: 750,
    image: '🏘️',
    available: 'Jan 1, 2025',
    utilities: 'Not Included',
    parking: true,
    laundry: 'In-building',
    petFriendly: false,
    furnished: false,
    distance: 0.5,
    amenities: ['WiFi', 'Storage', 'Backyard'],
    landlord: 'Dal Student Housing',
    description: 'Close to Dalhousie University. Perfect for students or roommates!'
  },
  // Quebec City Properties
  {
    id: 29,
    title: 'Old Quebec Apartment',
    address: '789 Rue Saint-Jean, Quebec City, QC',
    city: 'Quebec City',
    province: 'QC',
    rent: 1100,
    bedrooms: 1,
    bathrooms: 1,
    sqft: 500,
    image: '🏰',
    available: 'Available Now',
    utilities: 'Not Included',
    parking: false,
    laundry: 'Shared',
    petFriendly: false,
    furnished: false,
    distance: 2.5,
    amenities: ['WiFi', 'Historic Building', 'Hardwood Floors'],
    landlord: 'Vieux Quebec Properties',
    description: 'Charming apartment in historic Old Quebec. Unique character!'
  },
  {
    id: 30,
    title: 'Sainte-Foy Student Studio',
    address: '234 Chemin Sainte-Foy, Quebec City, QC',
    city: 'Quebec City',
    province: 'QC',
    rent: 850,
    bedrooms: 0,
    bathrooms: 1,
    sqft: 380,
    image: '🏠',
    available: 'Available Now',
    utilities: 'Included',
    parking: false,
    laundry: 'In-building',
    petFriendly: false,
    furnished: true,
    distance: 0.8,
    amenities: ['WiFi', 'Heating Included'],
    landlord: 'Laval Student Housing',
    description: 'Affordable studio near Université Laval. All utilities included!'
  },
  // More Toronto Properties
  {
    id: 31,
    title: 'Kensington Market Loft',
    address: '345 Augusta Ave, Toronto, ON',
    city: 'Toronto',
    province: 'ON',
    rent: 1950,
    bedrooms: 1,
    bathrooms: 1,
    sqft: 650,
    image: '🎨',
    available: 'Available Now',
    utilities: 'Not Included',
    parking: false,
    laundry: 'In-building',
    petFriendly: true,
    furnished: false,
    distance: 1.2,
    amenities: ['WiFi', 'Exposed Brick', 'High Ceilings'],
    landlord: 'Kensington Properties',
    description: 'Artistic loft in vibrant Kensington Market. Unique character!'
  },
  {
    id: 32,
    title: 'Etobicoke 2BR Family Home',
    address: '678 The Queensway, Toronto, ON',
    city: 'Toronto',
    province: 'ON',
    rent: 2000,
    bedrooms: 2,
    bathrooms: 2,
    sqft: 950,
    image: '🏡',
    available: 'Jan 1, 2025',
    utilities: 'Not Included',
    parking: true,
    laundry: 'In-unit',
    petFriendly: true,
    furnished: false,
    distance: 12.0,
    amenities: ['WiFi', 'Backyard', 'Storage', 'Garage'],
    landlord: 'West End Realty',
    description: 'Spacious family home in quiet Etobicoke neighborhood. Great for families!'
  },
  {
    id: 33,
    title: 'North York Condo',
    address: '901 Yonge St, Toronto, ON',
    city: 'Toronto',
    province: 'ON',
    rent: 1700,
    bedrooms: 1,
    bathrooms: 1,
    sqft: 580,
    image: '🏢',
    available: 'Available Now',
    utilities: 'Included',
    parking: true,
    laundry: 'In-unit',
    petFriendly: false,
    furnished: false,
    distance: 7.5,
    amenities: ['WiFi', 'Gym', 'Pool', 'Sauna'],
    landlord: 'North York Properties',
    description: 'Modern condo near subway. Easy commute to downtown!'
  },
  {
    id: 34,
    title: 'Leslieville 1BR Apartment',
    address: '234 Queen St E, Toronto, ON',
    city: 'Toronto',
    province: 'ON',
    rent: 1850,
    bedrooms: 1,
    bathrooms: 1,
    sqft: 600,
    image: '🏘️',
    available: 'Dec 1, 2024',
    utilities: 'Not Included',
    parking: false,
    laundry: 'In-building',
    petFriendly: true,
    furnished: false,
    distance: 4.0,
    amenities: ['WiFi', 'Balcony', 'Hardwood Floors'],
    landlord: 'East End Living',
    description: 'Trendy Leslieville location with cafes and shops nearby!'
  },
  // More Vancouver Properties
  {
    id: 35,
    title: 'Gastown Studio Loft',
    address: '567 Water St, Vancouver, BC',
    city: 'Vancouver',
    province: 'BC',
    rent: 1900,
    bedrooms: 0,
    bathrooms: 1,
    sqft: 450,
    image: '🏛️',
    available: 'Available Now',
    utilities: 'Included',
    parking: false,
    laundry: 'In-building',
    petFriendly: false,
    furnished: true,
    distance: 1.5,
    amenities: ['WiFi', 'Historic Building', 'Exposed Brick'],
    landlord: 'Gastown Heritage',
    description: 'Historic Gastown loft with character. Walk to everything!'
  },
  {
    id: 36,
    title: 'Burnaby 2BR Near SFU',
    address: '890 University Dr, Burnaby, BC',
    city: 'Burnaby',
    province: 'BC',
    rent: 1750,
    bedrooms: 2,
    bathrooms: 1,
    sqft: 800,
    image: '🏫',
    available: 'Jan 1, 2025',
    utilities: 'Not Included',
    parking: true,
    laundry: 'In-unit',
    petFriendly: true,
    furnished: false,
    distance: 0.4,
    amenities: ['WiFi', 'Gym', 'Study Room'],
    landlord: 'SFU Student Housing',
    description: 'Perfect for SFU students! Close to campus and transit.'
  },
  {
    id: 37,
    title: 'Richmond 3BR Townhouse',
    address: '123 Garden City Rd, Richmond, BC',
    city: 'Richmond',
    province: 'BC',
    rent: 2600,
    bedrooms: 3,
    bathrooms: 2,
    sqft: 1200,
    image: '🏘️',
    available: 'Available Now',
    utilities: 'Not Included',
    parking: true,
    laundry: 'In-unit',
    petFriendly: true,
    furnished: false,
    distance: 15.0,
    amenities: ['WiFi', 'Backyard', 'Storage', 'Garage'],
    landlord: 'Richmond Homes',
    description: 'Spacious townhouse perfect for families or roommates!'
  },
  {
    id: 38,
    title: 'Yaletown Luxury Studio',
    address: '456 Davie St, Vancouver, BC',
    city: 'Vancouver',
    province: 'BC',
    rent: 2100,
    bedrooms: 0,
    bathrooms: 1,
    sqft: 500,
    image: '💎',
    available: 'Available Now',
    utilities: 'Included',
    parking: true,
    laundry: 'In-unit',
    petFriendly: false,
    furnished: true,
    distance: 1.8,
    amenities: ['WiFi', 'Gym', 'Pool', 'Concierge', 'Rooftop'],
    landlord: 'Yaletown Luxury Living',
    description: 'Ultra-modern studio in upscale Yaletown. 5-star amenities!'
  },
  // More Montreal Properties
  {
    id: 39,
    title: 'Mile End 2BR',
    address: '789 Avenue du Parc, Montreal, QC',
    city: 'Montreal',
    province: 'QC',
    rent: 1350,
    bedrooms: 2,
    bathrooms: 1,
    sqft: 700,
    image: '🎨',
    available: 'Available Now',
    utilities: 'Not Included',
    parking: false,
    laundry: 'Shared',
    petFriendly: true,
    furnished: false,
    distance: 2.0,
    amenities: ['WiFi', 'Hardwood Floors', 'High Ceilings'],
    landlord: 'Mile End Rentals',
    description: 'Hip Mile End neighborhood with cafes, shops, and culture!'
  },
  {
    id: 40,
    title: 'Griffintown Modern 1BR',
    address: '234 Rue Wellington, Montreal, QC',
    city: 'Montreal',
    province: 'QC',
    rent: 1600,
    bedrooms: 1,
    bathrooms: 1,
    sqft: 600,
    image: '🏙️',
    available: 'Dec 15, 2024',
    utilities: 'Included',
    parking: true,
    laundry: 'In-unit',
    petFriendly: false,
    furnished: false,
    distance: 3.5,
    amenities: ['WiFi', 'Gym', 'Rooftop Terrace'],
    landlord: 'Griffintown Properties',
    description: 'Brand new condo in trendy Griffintown. Modern amenities!'
  },
  {
    id: 41,
    title: 'Verdun Affordable 2BR',
    address: '567 Rue de l\'Église, Montreal, QC',
    city: 'Montreal',
    province: 'QC',
    rent: 1100,
    bedrooms: 2,
    bathrooms: 1,
    sqft: 750,
    image: '🏡',
    available: 'Available Now',
    utilities: 'Not Included',
    parking: true,
    laundry: 'In-building',
    petFriendly: true,
    furnished: false,
    distance: 5.0,
    amenities: ['WiFi', 'Storage', 'Balcony'],
    landlord: 'Verdun Housing',
    description: 'Affordable 2-bedroom in up-and-coming Verdun. Great value!'
  },
  {
    id: 42,
    title: 'Outremont Elegant 1BR',
    address: '890 Avenue Bernard, Montreal, QC',
    city: 'Montreal',
    province: 'QC',
    rent: 1450,
    bedrooms: 1,
    bathrooms: 1,
    sqft: 650,
    image: '🏛️',
    available: 'Jan 1, 2025',
    utilities: 'Not Included',
    parking: false,
    laundry: 'In-building',
    petFriendly: false,
    furnished: false,
    distance: 3.0,
    amenities: ['WiFi', 'Hardwood Floors', 'Fireplace'],
    landlord: 'Outremont Estates',
    description: 'Elegant apartment in prestigious Outremont neighborhood!'
  },
  // More Calgary Properties
  {
    id: 43,
    title: 'Beltline 1BR Condo',
    address: '123 17th Ave SW, Calgary, AB',
    city: 'Calgary',
    province: 'AB',
    rent: 1500,
    bedrooms: 1,
    bathrooms: 1,
    sqft: 600,
    image: '🏙️',
    available: 'Available Now',
    utilities: 'Included',
    parking: true,
    laundry: 'In-unit',
    petFriendly: true,
    furnished: false,
    distance: 2.0,
    amenities: ['WiFi', 'Gym', 'Pool', 'Party Room'],
    landlord: 'Beltline Living',
    description: 'Vibrant Beltline location with nightlife and restaurants!'
  },
  {
    id: 44,
    title: 'Kensington 2BR House',
    address: '456 Kensington Rd NW, Calgary, AB',
    city: 'Calgary',
    province: 'AB',
    rent: 1900,
    bedrooms: 2,
    bathrooms: 2,
    sqft: 900,
    image: '🏡',
    available: 'Dec 1, 2024',
    utilities: 'Not Included',
    parking: true,
    laundry: 'In-unit',
    petFriendly: true,
    furnished: false,
    distance: 3.5,
    amenities: ['WiFi', 'Backyard', 'Storage', 'Fireplace'],
    landlord: 'Kensington Homes',
    description: 'Charming house in trendy Kensington. Walk to shops and cafes!'
  },
  {
    id: 45,
    title: 'Inglewood Studio',
    address: '789 9th Ave SE, Calgary, AB',
    city: 'Calgary',
    province: 'AB',
    rent: 1200,
    bedrooms: 0,
    bathrooms: 1,
    sqft: 400,
    image: '🏠',
    available: 'Available Now',
    utilities: 'Included',
    parking: false,
    laundry: 'In-building',
    petFriendly: false,
    furnished: true,
    distance: 4.0,
    amenities: ['WiFi', 'Heating Included'],
    landlord: 'Inglewood Properties',
    description: 'Cozy studio in historic Inglewood. Artistic community!'
  },
  // Saskatoon Properties
  {
    id: 46,
    title: 'Broadway District 1BR',
    address: '234 Broadway Ave, Saskatoon, SK',
    city: 'Saskatoon',
    province: 'SK',
    rent: 1050,
    bedrooms: 1,
    bathrooms: 1,
    sqft: 550,
    image: '🏢',
    available: 'Available Now',
    utilities: 'Not Included',
    parking: true,
    laundry: 'In-building',
    petFriendly: true,
    furnished: false,
    distance: 1.5,
    amenities: ['WiFi', 'Storage'],
    landlord: 'Broadway Rentals',
    description: 'Great location in Broadway District. Close to U of S!'
  },
  {
    id: 47,
    title: 'U of S Campus Studio',
    address: '567 College Dr, Saskatoon, SK',
    city: 'Saskatoon',
    province: 'SK',
    rent: 850,
    bedrooms: 0,
    bathrooms: 1,
    sqft: 350,
    image: '🏫',
    available: 'Jan 1, 2025',
    utilities: 'Included',
    parking: false,
    laundry: 'In-building',
    petFriendly: false,
    furnished: false,
    distance: 0.2,
    amenities: ['WiFi', 'Study Room'],
    landlord: 'U of S Housing',
    description: 'Steps from campus! Perfect for students. Utilities included!'
  },
  // Regina Properties
  {
    id: 48,
    title: 'Downtown Regina 2BR',
    address: '890 Victoria Ave, Regina, SK',
    city: 'Regina',
    province: 'SK',
    rent: 1150,
    bedrooms: 2,
    bathrooms: 1,
    sqft: 800,
    image: '🏙️',
    available: 'Available Now',
    utilities: 'Not Included',
    parking: true,
    laundry: 'In-unit',
    petFriendly: true,
    furnished: false,
    distance: 2.0,
    amenities: ['WiFi', 'Gym', 'Storage'],
    landlord: 'Regina Downtown Properties',
    description: 'Spacious downtown apartment. Close to everything!'
  },
  {
    id: 49,
    title: 'U of R Student 1BR',
    address: '123 Wascana Pkwy, Regina, SK',
    city: 'Regina',
    province: 'SK',
    rent: 950,
    bedrooms: 1,
    bathrooms: 1,
    sqft: 500,
    image: '🏫',
    available: 'Available Now',
    utilities: 'Included',
    parking: true,
    laundry: 'In-building',
    petFriendly: false,
    furnished: false,
    distance: 0.5,
    amenities: ['WiFi', 'Study Room'],
    landlord: 'University Housing',
    description: 'Close to University of Regina. Great for students!'
  },
  // Victoria Properties
  {
    id: 50,
    title: 'Downtown Victoria Studio',
    address: '456 Government St, Victoria, BC',
    city: 'Victoria',
    province: 'BC',
    rent: 1400,
    bedrooms: 0,
    bathrooms: 1,
    sqft: 400,
    image: '🏛️',
    available: 'Available Now',
    utilities: 'Included',
    parking: false,
    laundry: 'In-building',
    petFriendly: false,
    furnished: true,
    distance: 1.0,
    amenities: ['WiFi', 'Historic Building'],
    landlord: 'Victoria Heritage',
    description: 'Charming studio in beautiful downtown Victoria!'
  },
  {
    id: 51,
    title: 'UVic Campus 1BR',
    address: '789 Sinclair Rd, Victoria, BC',
    city: 'Victoria',
    province: 'BC',
    rent: 1300,
    bedrooms: 1,
    bathrooms: 1,
    sqft: 500,
    image: '🏫',
    available: 'Dec 1, 2024',
    utilities: 'Not Included',
    parking: true,
    laundry: 'In-building',
    petFriendly: true,
    furnished: false,
    distance: 0.3,
    amenities: ['WiFi', 'Bike Storage'],
    landlord: 'UVic Student Housing',
    description: 'Perfect for UVic students! Walk to campus.'
  },
  {
    id: 52,
    title: 'James Bay 2BR',
    address: '234 Menzies St, Victoria, BC',
    city: 'Victoria',
    province: 'BC',
    rent: 1800,
    bedrooms: 2,
    bathrooms: 1,
    sqft: 750,
    image: '🏘️',
    available: 'Available Now',
    utilities: 'Not Included',
    parking: true,
    laundry: 'In-unit',
    petFriendly: true,
    furnished: false,
    distance: 2.5,
    amenities: ['WiFi', 'Ocean View', 'Balcony'],
    landlord: 'James Bay Properties',
    description: 'Beautiful James Bay location near the ocean!'
  },
  // St. John\'s Properties
  {
    id: 53,
    title: 'Downtown St. John\'s 1BR',
    address: '567 Water St, St. John\'s, NL',
    city: 'St. John\'s',
    province: 'NL',
    rent: 1100,
    bedrooms: 1,
    bathrooms: 1,
    sqft: 550,
    image: '🏛️',
    available: 'Available Now',
    utilities: 'Included',
    parking: false,
    laundry: 'In-building',
    petFriendly: true,
    furnished: false,
    distance: 1.5,
    amenities: ['WiFi', 'Historic Building'],
    landlord: 'Downtown Properties NL',
    description: 'Historic downtown location with character and charm!'
  },
  {
    id: 54,
    title: 'MUN Campus Studio',
    address: '890 Elizabeth Ave, St. John\'s, NL',
    city: 'St. John\'s',
    province: 'NL',
    rent: 900,
    bedrooms: 0,
    bathrooms: 1,
    sqft: 380,
    image: '🏫',
    available: 'Jan 1, 2025',
    utilities: 'Included',
    parking: true,
    laundry: 'In-building',
    petFriendly: false,
    furnished: true,
    distance: 0.4,
    amenities: ['WiFi', 'Heating Included'],
    landlord: 'MUN Student Housing',
    description: 'Perfect for MUN students! All utilities included.'
  },
  // Kitchener-Waterloo Properties
  {
    id: 55,
    title: 'Uptown Waterloo 1BR',
    address: '123 King St N, Waterloo, ON',
    city: 'Waterloo',
    province: 'ON',
    rent: 1350,
    bedrooms: 1,
    bathrooms: 1,
    sqft: 600,
    image: '🏙️',
    available: 'Available Now',
    utilities: 'Not Included',
    parking: true,
    laundry: 'In-unit',
    petFriendly: false,
    furnished: false,
    distance: 0.8,
    amenities: ['WiFi', 'Gym', 'Storage'],
    landlord: 'Uptown Living',
    description: 'Modern condo near UW and WLU. Great location!'
  },
  {
    id: 56,
    title: 'Laurier Student House',
    address: '456 University Ave W, Waterloo, ON',
    city: 'Waterloo',
    province: 'ON',
    rent: 750,
    bedrooms: 1,
    bathrooms: 1,
    sqft: 400,
    image: '🏡',
    available: 'Available Now',
    utilities: 'Not Included',
    parking: false,
    laundry: 'Shared',
    petFriendly: false,
    furnished: false,
    distance: 0.3,
    amenities: ['WiFi', 'Backyard Access'],
    landlord: 'Student Housing Co-op',
    description: 'Affordable student housing near Laurier campus!'
  },
  {
    id: 57,
    title: 'Kitchener Downtown 2BR',
    address: '789 King St W, Kitchener, ON',
    city: 'Kitchener',
    province: 'ON',
    rent: 1600,
    bedrooms: 2,
    bathrooms: 1,
    sqft: 850,
    image: '🏢',
    available: 'Dec 15, 2024',
    utilities: 'Included',
    parking: true,
    laundry: 'In-unit',
    petFriendly: true,
    furnished: false,
    distance: 3.0,
    amenities: ['WiFi', 'Gym', 'Pool', 'Balcony'],
    landlord: 'KW Properties',
    description: 'Modern downtown Kitchener condo. All amenities!'
  },
  // London Properties
  {
    id: 58,
    title: 'Western University 1BR',
    address: '234 Richmond St, London, ON',
    city: 'London',
    province: 'ON',
    rent: 1200,
    bedrooms: 1,
    bathrooms: 1,
    sqft: 550,
    image: '🏫',
    available: 'Available Now',
    utilities: 'Not Included',
    parking: true,
    laundry: 'In-building',
    petFriendly: false,
    furnished: false,
    distance: 0.6,
    amenities: ['WiFi', 'Study Room'],
    landlord: 'Western Student Housing',
    description: 'Close to Western University. Perfect for students!'
  },
  {
    id: 59,
    title: 'Old East Village Studio',
    address: '567 Dundas St, London, ON',
    city: 'London',
    province: 'ON',
    rent: 950,
    bedrooms: 0,
    bathrooms: 1,
    sqft: 400,
    image: '🎨',
    available: 'Available Now',
    utilities: 'Included',
    parking: false,
    laundry: 'In-building',
    petFriendly: true,
    furnished: true,
    distance: 2.0,
    amenities: ['WiFi', 'Hardwood Floors'],
    landlord: 'Old East Properties',
    description: 'Artistic Old East Village. Cafes and galleries nearby!'
  },
  {
    id: 60,
    title: 'Downtown London 2BR',
    address: '890 King St, London, ON',
    city: 'London',
    province: 'ON',
    rent: 1550,
    bedrooms: 2,
    bathrooms: 1,
    sqft: 800,
    image: '🏙️',
    available: 'Jan 1, 2025',
    utilities: 'Not Included',
    parking: true,
    laundry: 'In-unit',
    petFriendly: true,
    furnished: false,
    distance: 3.5,
    amenities: ['WiFi', 'Gym', 'Storage', 'Balcony'],
    landlord: 'London Downtown Living',
    description: 'Spacious downtown apartment. Great amenities!'
  }
];

// GET /api/properties - Get all properties with filtering
router.get('/', async (req, res) => {
  try {
    const { city, maxRent, bedrooms, minBedrooms, maxBedrooms, utilities, parking, petFriendly } = req.query;
    
    let filteredProperties = [...properties];
    
    // Filter by city
    if (city) {
      filteredProperties = filteredProperties.filter(prop => 
        prop.city.toLowerCase().includes(city.toLowerCase())
      );
    }
    
    // Filter by max rent
    if (maxRent) {
      filteredProperties = filteredProperties.filter(prop => 
        prop.rent <= parseInt(maxRent)
      );
    }
    
    // Filter by bedrooms
    if (bedrooms) {
      filteredProperties = filteredProperties.filter(prop => 
        prop.bedrooms === parseInt(bedrooms)
      );
    }
    
    if (minBedrooms) {
      filteredProperties = filteredProperties.filter(prop => 
        prop.bedrooms >= parseInt(minBedrooms)
      );
    }
    
    if (maxBedrooms) {
      filteredProperties = filteredProperties.filter(prop => 
        prop.bedrooms <= parseInt(maxBedrooms)
      );
    }
    
    // Filter by utilities
    if (utilities === 'included') {
      filteredProperties = filteredProperties.filter(prop => 
        prop.utilities === 'Included'
      );
    }
    
    // Filter by parking
    if (parking === 'true') {
      filteredProperties = filteredProperties.filter(prop => prop.parking);
    }
    
    // Filter by pet friendly
    if (petFriendly === 'true') {
      filteredProperties = filteredProperties.filter(prop => prop.petFriendly);
    }
    
    // Add AI quality scores to properties
    const propertiesWithAI = await Promise.all(
      filteredProperties.map(async (prop) => {
        try {
          const analysis = await imageAnalysisService.analyzePropertyImage(prop.image);
          return {
            ...prop,
            aiAnalysis: analysis.success ? {
              qualityScore: analysis.analysis.qualityScore,
              confidence: analysis.analysis.confidence,
              highlights: analysis.analysis.highlights,
              detectedIssues: analysis.analysis.detectedIssues
            } : null
          };
        } catch (error) {
          console.error(`Error analyzing property ${prop.id}:`, error);
          return prop;
        }
      })
    );

    res.json({
      success: true,
      count: propertiesWithAI.length,
      properties: propertiesWithAI
    });
  } catch (error) {
    res.status(500).json({
      success: false,
      message: 'Error fetching properties',
      error: error.message
    });
  }
});

// GET /api/properties/:id - Get single property by ID
router.get('/:id', (req, res) => {
  try {
    const { id } = req.params;
    const property = properties.find(p => p.id === parseInt(id));
    
    if (!property) {
      return res.status(404).json({
        success: false,
        message: 'Property not found'
      });
    }
    
    res.json({
      success: true,
      property
    });
  } catch (error) {
    res.status(500).json({
      success: false,
      message: 'Error fetching property',
      error: error.message
    });
  }
});

// POST /api/properties
router.post('/', (req, res) => {
  // TODO: Implement property creation
  res.json({
    success: true,
    message: 'Property created successfully',
    property: req.body
  });
});

module.exports = router;
